### PR TITLE
[DOC] Update README to point to `sktime`

### PR DESCRIPTION
**Pull request by fkiraly**
`vmdpy` is maintained in `sktime` since August 2023, see https://github.com/sktime/sktime/issues/5137

This has not been clearly signposted on the original repository, which has led to some issues being opened here.

This PR updates the README in this repository with clear pointers.

I would further suggest, @vrcarva:

* if you give me write or issue moderation access to this repo, I can transfer all remaining issues to the `sktime` issue tracker and handle them there
* after this is done, I would suggest archiving this repo so no new issues can be opened - this will ensure new issues and PR are opened only on `sktime`.

### CODE REVIEW

**Comment by vrcarva** [comment]
Done! Thanks, @fkiraly :)

**Comment by fkiraly** [comment]
Thanks!

Shall we proceed moving issues to `sktime`, and I answer there?
Needs to be done by someone with write access to both repos, so you could invite me to this one until the issues are transferred.

**Comment by vrcarva** [comment]
Sure! I had invited you, can you check if you received it?

**Comment by fkiraly** [comment]
yes, thanks. Starting to transfer the issues now.

**Comment by fkiraly** [comment]
Hm, that does not work. I was not aware that transferring issues is possible only between repositories in the same organization.
https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
Apologies for not being aware of this.

There is, hence, only one way if we still want to do this: transferring the repository to the `sktime` org, at least temporarily.
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository
This would give me admin access to your repo, rather than just write, with a variety of options for destructive actions attached.

Now, I would promise to use this only for transferring the issues and transfer the repo back if you want, but I would understand if that is not something you would be comfortable doing - up to you. If you decide to do this, there's a very narrow one-day limit to accept the transfer, for security reasons, so doing it twice would require some planning and scheduling a time window ahead. Perhaps a screenshare where we do the entire back and forth in 15-30min? As said, we can leave it as well if you prefer not to.

**Comment by vrcarva** [comment]
No problem! This sounds like a good solution. When can we set up a time to do the transfer? My schedule for the next few days is flexible, and I'm probably 1 hour ahead of you, in CET.

**Comment by fkiraly** [comment]
Sorry, I did miss this message.

How about June 14, 14 UTC, or June 17, anytime 11-12, or 14?
It is maybe easier to send direct messages on the sktime discord: https://discord.com/invite/54ACzaFsn7

**Pull request merged**
